import localFont from "next/font/local";
import "./globals.css";
import Script from "next/script";

const redHatText = localFont({
  src: "./assets/fonts/RedHatText-VariableFont_wght.ttf",
  variable: "--font-red-hat",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${redHatText.variable}  antialiased`}>{children}</body>
      <Script
        type="module"
        src="https://cdn.jsdelivr.net/npm/ionicons@latest/dist/ionicons/ionicons.esm.js"
      />
      <Script
        nomodule
        src="https://cdn.jsdelivr.net/npm/ionicons@latest/dist/ionicons/ionicons.js"
      />
    </html>
  );
}
